apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ include "tempchart.fullname" . }}
  labels:
  {{- include "tempchart.labels" . | nindent 4 }}
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>K8S Nginx</title>
    </head>
    <body>
      <h2>Hello Stef</h2>
    </body>
    </html>